### ISSUE TITLE
Support for keyboard layouts other than qwerty

### ISSUE THREAD

**Issue by VedVid** [VedVid/RogueRobsTrains#4]
Recently, I accepted @anaseto's PR about using runes instead of using bearlibterminal scan codes directly. Later, I started to widen the support for runes, but it started to be a bit unconvenient (didn't work well with existing systems - and I'd like to add non-qwerty support to RAWIG as well). Also: "this means that in some keyboard layouts the WASD keys will not be in a sensible position, but at least they're where you expect".

So, why not to get both: sensible layouts and proper layout mapping? I started to work on this recently. It's a bit pain to implement (because I'm mapping every control scheme manually) and still in early stage, but it seem to work as expected. (One may want to check keyboardLayoutConfig2 branch.)

QWERTZ is based on German scheme; AZERTY - the French one.

There are still dilemmas to resolve, thought. For example, using AZERTY one need to press shift to write numbers. Therefore, I'd assume that "default key" is, for example, 'é', not '2'.  
On the instructions panel, I wrote all special (ie not related to movement) commands their keys. So, 1 - switch to primary weapon, 2 - switch to secondary, etc. The question is: would it be more clear (even if both '2' and 'é' are supported), for AZERTY-user, to have 'é' as part of this string instead of '2'?

![image](https://user-images.githubusercontent.com/16949680/56240449-df0ad980-6093-11e9-90d0-cb994bff3f74.png)

Personally, this change doesn't seem sensible for me, but I'm using QWERTY all my life, so I'd like to consult it with actual AZERTY users.

**Comment by anaseto** [comment]
Hi, I tested your new system, seems to work ok, it's a nice touch to provide specific improvements for some common layouts!

With respect to your AZERTY question, I think there's no definitive answer, some will prefer to remap keys to direct access while others may not (I've done it sometimes with my layout, which also needs shift for numbers, though it depends on whether some common special characters are actually more used: in your game I think what you did is ok). That said, the same is true for other keys in fact: I've actually been in both positions: now I tend to use hjkl even though they're not in sensible positions in my layout (french dvorak variant bépo), because even if it was strange at the beginning, now I can use the same in most roguelikes without  changing my layout nor their settings (which many roguelikes do not allow anyways), as long as they use rune-based input for characters by default.

A complementary approach (I did that in Boohu, but not very well, which reminds me I should someday improve my system) is to allow people to change keybindings for characters for each action (best case in-game, because some players are sometimes affraid of config files).

**Comment by VedVid** [comment]
> seems to work ok

I'm glad to have it confirmed :)

For now, I'm mapping shifted and shiftless ( :P ) to the same scan codes. The remaining problem is how to present it visually. Support for other than most popular layouts is hard to provide for me, using current approach. Given your comment, I see what problems reading runes can solve. 

I'm working on custom keybindings already (using config file for now - I'd like to add in-game options menu later, though), but somehow... it fallbacks to QWERTY all the time.

**Comment by anaseto** [comment]
> For now, I'm mapping shifted and shiftless ( :P ) to the same scan codes.

This is indeed a good thing as long as it's possible, which for your game seems to be the case with all keyboard layouts I know of.

**Comment by VedVid** [comment]
"numbers" is way to go
